package builder

import (
	"context"
	"fmt"
	"strings"

	"github.com/rs/zerolog/log"
)

const nginxSitesDir = "/etc/nginx/conf.d/sites"
const nginxConfTemplate = `# Auto-generated by PolyON — %s
server {
    listen 80;
    server_name %s;

    root /data/sites/%s/dist;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ $uri.html /index.html;
    }

    # Cache static assets
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?|ttf|eot)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
}
`

// GenerateNginxConfig creates an nginx vhost config for a site.
func (b *Builder) GenerateNginxConfig(ctx context.Context, siteID, slug, domain string) error {
	serverName := slug + ".polyon.local"
	if domain != "" {
		serverName = domain + " " + slug + ".polyon.local"
	}

	conf := fmt.Sprintf(nginxConfTemplate, slug, serverName, siteID)
	fileName := slug + ".conf"

	// Write config to polyon-console container
	sdk := b.docker.SDK()
	if sdk == nil {
		return fmt.Errorf("docker not available")
	}

	// Use docker exec to write the file
	writeCmd := fmt.Sprintf("mkdir -p %s && cat > %s/%s << 'NGINX_EOF'\n%sNGINX_EOF",
		nginxSitesDir, nginxSitesDir, fileName, conf)

	_, err := b.execNginxCmd(ctx, writeCmd)
	if err != nil {
		return fmt.Errorf("write nginx config: %w", err)
	}

	// Ensure nginx includes sites dir
	_, _ = b.execNginxCmd(ctx,
		`grep -q "include /etc/nginx/conf.d/sites/*.conf;" /etc/nginx/conf.d/default.conf || `+
			`echo 'include /etc/nginx/conf.d/sites/*.conf;' >> /etc/nginx/conf.d/default.conf`)

	// Reload nginx
	_, err = b.execNginxCmd(ctx, "nginx -s reload 2>&1")
	if err != nil {
		log.Warn().Err(err).Msg("nginx reload failed, trying nginx -t first")
		out, _ := b.execNginxCmd(ctx, "nginx -t 2>&1")
		return fmt.Errorf("nginx reload: %w\n%s", err, out)
	}

	log.Info().Str("slug", slug).Str("domain", serverName).Msg("nginx vhost created")
	return nil
}

// RemoveNginxConfig removes an nginx vhost config.
func (b *Builder) RemoveNginxConfig(ctx context.Context, slug string) error {
	_, err := b.execNginxCmd(ctx,
		fmt.Sprintf("rm -f %s/%s.conf && nginx -s reload 2>&1", nginxSitesDir, slug))
	return err
}

func (b *Builder) execNginxCmd(ctx context.Context, cmd string) (string, error) {
	return b.docker.ExecCommand("polyon-console", "sh", "-c", cmd)
}

// DeploySite runs the full deploy: generate nginx config + log.
func (b *Builder) DeploySite(ctx context.Context, siteID, slug, domain string) error {
	// Ensure /data/sites mount exists in polyon-console
	// (This needs to be a shared volume between build container and polyon-console)

	if err := b.GenerateNginxConfig(ctx, siteID, slug, domain); err != nil {
		return err
	}
	return nil
}

// buildKey for log message
func siteURL(slug string, domain *string) string {
	urls := []string{"https://" + slug + ".polyon.local"}
	if domain != nil && *domain != "" {
		urls = append([]string{"https://" + *domain}, urls...)
	}
	return strings.Join(urls, ", ")
}