// Package traefik — generator.go
// Generates the full set of Traefik dynamic-config YAML files from a
// GeneratorConfig snapshot of the current DB state.
package traefik

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/rs/zerolog/log"
	"gopkg.in/yaml.v3"
)

const fileHeader = "# Auto-generated by PolyON Core — do not edit manually\n"

// GeneratorConfig holds all the information needed to render the
// /traefik-dynamic/ directory from scratch.
type GeneratorConfig struct {
	OutputDir      string // default: /traefik-dynamic
	BaseDomain     string // e.g. "cmars.com"
	ConsoleDomain  string // e.g. "console.cmars.com"
	PortalDomain   string // e.g. "portal.cmars.com"
	MailDomain     string // e.g. "mail.cmars.kr"
	CertFile       string // wildcard cert path
	KeyFile        string // wildcard key path
	ForwardAuthURL string // assembled by caller from DB "core" service
	Apps           []AppRoute
	InfraServices  []InfraService // DB-sourced infra service definitions
	MailEnabled    bool           // generate 40-mail-tcp.yml
}

// AppRoute describes a single application's routing configuration.
type AppRoute struct {
	ID         string // e.g. "chat"
	Subdomain  string // e.g. "chat"
	BackendURL string // e.g. "http://polyon-chat:8065"
}

// InfraService mirrors store.InfraService for the traefik package.
type InfraService struct {
	ID         string
	Name       string
	Host       string
	Port       int
	Protocol   string     // "http" | "tcp"
	Category   string     // "infra" | "monitoring" | "mail-tcp"
	EntryPoint string
	PathRules  []PathRule // parsed from JSON stored in DB
	Enabled    bool
}

// PathRule represents one path-based routing rule for an infra service.
type PathRule struct {
	Path     string `json:"path"`
	Priority int    `json:"priority"`
	Service  string `json:"service,omitempty"` // override service name (default: svc.ID)
}

func (c *GeneratorConfig) outputDir() string {
	if c.OutputDir == "" {
		return "/traefik-dynamic"
	}
	return c.OutputDir
}

// Generate writes all dynamic-config files to cfg.OutputDir.
func Generate(cfg GeneratorConfig) error {
	if err := os.MkdirAll(cfg.outputDir(), 0o755); err != nil {
		return fmt.Errorf("traefik generate: mkdir %s: %w", cfg.outputDir(), err)
	}
	steps := []func() error{
		func() error { return generate00Infra(cfg) },
		func() error { return generate10Apps(cfg) },
		func() error { return generate20Auth(cfg) },
		func() error { return generate30Monitoring(cfg) },
		func() error { return generate40MailTCP(cfg) },
		func() error { return generate50TLS(cfg) },
	}
	for _, fn := range steps {
		if err := fn(); err != nil {
			return err
		}
	}
	return nil
}

// ── 00-infra.yml ─────────────────────────────────────────────────────────────

func generate00Infra(cfg GeneratorConfig) error {
	type infraHTTP struct {
		Middlewares map[string]middlewareConfig `yaml:"middlewares,omitempty"`
		Routers     map[string]routerConfig     `yaml:"routers,omitempty"`
		Services    map[string]serviceConfig    `yaml:"services,omitempty"`
	}
	type infraConfig struct {
		HTTP infraHTTP `yaml:"http"`
	}

	infraServices := filterByCategory(cfg.InfraServices, "infra")

	// Build services map from DB
	services := map[string]serviceConfig{}
	for _, svc := range infraServices {
		services[svc.ID] = serviceConfig{
			LoadBalancer: lbConfig{Servers: []serverConfig{{
				URL: fmt.Sprintf("http://%s:%d", svc.Host, svc.Port),
			}}},
		}
	}

	// Build :1111 management routers from PathRules
	routers := map[string]routerConfig{}
	for _, svc := range infraServices {
		if len(svc.PathRules) == 0 {
			log.Warn().Str("service", svc.ID).Msg("generate00Infra: no path rules, skipping management routers")
			continue
		}
		for i, rule := range svc.PathRules {
			routerName := svc.ID
			if i > 0 {
				routerName = fmt.Sprintf("%s-%d", svc.ID, i)
			}
			targetService := svc.ID
			if rule.Service != "" {
				targetService = rule.Service
			}
			routers[routerName] = routerConfig{
				Rule:        fmt.Sprintf("PathPrefix(`%s`)", rule.Path),
				EntryPoints: []string{svc.EntryPoint},
				Service:     targetService,
				Middlewares: []string{"https-headers"},
				Priority:    rule.Priority,
			}
		}
	}

	// Determine service IDs for console/portal domain routers
	uiSvcID := findServiceByID(infraServices, "ui")
	authSvcID := findServiceByID(infraServices, "auth")
	coreSvcID := findServiceByID(infraServices, "core")

	tls := &tlsConfig{}

	// Console domain routers (websecure)
	if cfg.ConsoleDomain != "" {
		routers["console-domain"] = routerConfig{
			Rule:        fmt.Sprintf("Host(`%s`)", cfg.ConsoleDomain),
			EntryPoints: []string{"websecure"},
			Service:     uiSvcID,
			Middlewares: []string{"https-headers"},
			TLS:         tls,
			Priority:    10,
		}
		routers["console-domain-auth"] = routerConfig{
			Rule:        fmt.Sprintf("Host(`%s`) && PathPrefix(`/auth`)", cfg.ConsoleDomain),
			EntryPoints: []string{"websecure"},
			Service:     authSvcID,
			Middlewares: []string{"https-headers"},
			TLS:         tls,
			Priority:    100,
		}
		routers["console-domain-api"] = routerConfig{
			Rule:        fmt.Sprintf("Host(`%s`) && PathPrefix(`/api`)", cfg.ConsoleDomain),
			EntryPoints: []string{"websecure"},
			Service:     coreSvcID,
			Middlewares: []string{"https-headers"},
			TLS:         tls,
			Priority:    50,
		}
	}

	// Portal domain routers (websecure)
	if cfg.PortalDomain != "" {
		routers["portal"] = routerConfig{
			Rule:        fmt.Sprintf("Host(`%s`)", cfg.PortalDomain),
			EntryPoints: []string{"websecure"},
			Service:     uiSvcID,
			Middlewares: []string{"https-headers"},
			TLS:         tls,
			Priority:    10,
		}
		routers["portal-auth"] = routerConfig{
			Rule:        fmt.Sprintf("Host(`%s`) && PathPrefix(`/auth`)", cfg.PortalDomain),
			EntryPoints: []string{"websecure"},
			Service:     authSvcID,
			Middlewares: []string{"https-headers"},
			TLS:         tls,
			Priority:    100,
		}
		routers["portal-api"] = routerConfig{
			Rule:        fmt.Sprintf("Host(`%s`) && PathPrefix(`/api`)", cfg.PortalDomain),
			EntryPoints: []string{"websecure"},
			Service:     coreSvcID,
			Middlewares: []string{"https-headers"},
			TLS:         tls,
			Priority:    50,
		}
	}

	doc := infraConfig{
		HTTP: infraHTTP{
			Middlewares: map[string]middlewareConfig{
				"https-headers": {
					Headers: &headersConfig{
						CustomRequestHeaders: map[string]string{
							"X-Forwarded-Proto": "https",
						},
					},
				},
			},
			Routers:  routers,
			Services: services,
		},
	}

	return writeYAML(cfg.outputDir(), "00-infra.yml", doc)
}

// ── 10-apps.yml ──────────────────────────────────────────────────────────────

func generate10Apps(cfg GeneratorConfig) error {
	type appsHTTP struct {
		Routers  map[string]routerConfig  `yaml:"routers,omitempty"`
		Services map[string]serviceConfig `yaml:"services,omitempty"`
	}
	type appsConfig struct {
		HTTP appsHTTP `yaml:"http"`
	}

	routers := make(map[string]routerConfig)
	services := make(map[string]serviceConfig)

	for _, app := range cfg.Apps {
		rKey := "app-" + sanitizeKey(app.ID)
		sKey := rKey + "-svc"
		routers[rKey] = routerConfig{
			Rule:        fmt.Sprintf("Host(`%s.%s`)", app.Subdomain, cfg.BaseDomain),
			EntryPoints: []string{"websecure"},
			Service:     sKey,
			Middlewares: []string{"forward-auth"},
			TLS:         &tlsConfig{},
			Priority:    20,
		}
		services[sKey] = serviceConfig{
			LoadBalancer: lbConfig{Servers: []serverConfig{{URL: app.BackendURL}}},
		}
	}

	doc := appsConfig{
		HTTP: appsHTTP{
			Routers:  routers,
			Services: services,
		},
	}
	return writeYAML(cfg.outputDir(), "10-apps.yml", doc)
}

// ── 20-auth.yml ──────────────────────────────────────────────────────────────

func generate20Auth(cfg GeneratorConfig) error {
	type authHTTP struct {
		Middlewares map[string]middlewareConfig `yaml:"middlewares,omitempty"`
		Routers     map[string]routerConfig     `yaml:"routers,omitempty"`
		Services    map[string]serviceConfig    `yaml:"services,omitempty"`
	}
	type authConfig struct {
		HTTP authHTTP `yaml:"http"`
	}

	// Find the UI service to use as wildcard-catchall backend
	infraServices := filterByCategory(cfg.InfraServices, "infra")
	uiSvcID := findServiceByID(infraServices, "ui")
	uiURL := ""
	for _, svc := range infraServices {
		if svc.ID == "ui" {
			uiURL = fmt.Sprintf("http://%s:%d", svc.Host, svc.Port)
			break
		}
	}

	// Build services map: only add if we have a UI service URL
	services := map[string]serviceConfig{}
	if uiURL != "" {
		services[uiSvcID] = serviceConfig{
			LoadBalancer: lbConfig{Servers: []serverConfig{{URL: uiURL}}},
		}
	}

	doc := authConfig{
		HTTP: authHTTP{
			Middlewares: map[string]middlewareConfig{
				"forward-auth": {
					ForwardAuth: &forwardAuthConfig{
						Address:             cfg.ForwardAuthURL,
						TrustForwardHeader:  true,
						AuthResponseHeaders: []string{"X-Auth-User", "X-Auth-Realm"},
					},
				},
			},
			Routers: map[string]routerConfig{
				"wildcard-catchall": {
					Rule:        fmt.Sprintf("HostRegexp(`{host:.+}.%s`)", cfg.BaseDomain),
					EntryPoints: []string{"websecure"},
					Service:     uiSvcID,
					Middlewares: []string{"forward-auth"},
					TLS:         &tlsConfig{},
					Priority:    1,
				},
			},
			Services: services,
		},
	}
	return writeYAML(cfg.outputDir(), "20-auth.yml", doc)
}

// ── 30-monitoring.yml ────────────────────────────────────────────────────────

func generate30Monitoring(cfg GeneratorConfig) error {
	type monitoringHTTP struct {
		Routers  map[string]routerConfig  `yaml:"routers,omitempty"`
		Services map[string]serviceConfig `yaml:"services,omitempty"`
	}
	type monitoringConfig struct {
		HTTP monitoringHTTP `yaml:"http"`
	}

	monitoringServices := filterByCategory(cfg.InfraServices, "monitoring")

	routers := map[string]routerConfig{}
	services := map[string]serviceConfig{}

	for _, svc := range monitoringServices {
		routerName := svc.ID
		svcName := svc.ID + "-svc"

		routers[routerName] = routerConfig{
			Rule:        "PathPrefix(`/`)",
			EntryPoints: []string{svc.EntryPoint},
			Service:     svcName,
			Middlewares: []string{"https-headers"},
		}

		services[svcName] = serviceConfig{
			LoadBalancer: lbConfig{Servers: []serverConfig{{
				URL: fmt.Sprintf("http://%s:%d", svc.Host, svc.Port),
			}}},
		}
	}

	// Traefik dashboard is special (api@internal) — hardcoded by design
	routers["traefik-dashboard"] = routerConfig{
		Rule:        "PathPrefix(`/`)",
		EntryPoints: []string{"traefik-dash"},
		Service:     "api@internal",
	}
	routers["traefik-api-internal"] = routerConfig{
		Rule:        "PathPrefix(`/api`)",
		EntryPoints: []string{"traefik-dash"},
		Service:     "api@internal",
	}

	doc := monitoringConfig{
		HTTP: monitoringHTTP{
			Routers:  routers,
			Services: services,
		},
	}
	return writeYAML(cfg.outputDir(), "30-monitoring.yml", doc)
}

// ── 40-mail-tcp.yml ──────────────────────────────────────────────────────────

// tcpRouterConfig is a TCP-level router (distinct from the HTTP routerConfig).
type tcpRouterConfig struct {
	Rule        string        `yaml:"rule"`
	EntryPoints []string      `yaml:"entryPoints"`
	Service     string        `yaml:"service"`
	TLS         *tcpTLSConfig `yaml:"tls,omitempty"`
}

type tcpTLSConfig struct {
	Passthrough bool `yaml:"passthrough"`
}

type tcpServiceConfig struct {
	LoadBalancer tcpLBConfig `yaml:"loadBalancer"`
}

type tcpLBConfig struct {
	Servers []tcpServerConfig `yaml:"servers"`
}

type tcpServerConfig struct {
	Address string `yaml:"address"`
}

type tcpConfig struct {
	Routers  map[string]tcpRouterConfig  `yaml:"routers,omitempty"`
	Services map[string]tcpServiceConfig `yaml:"services,omitempty"`
}

type mailTCPFile struct {
	TCP tcpConfig `yaml:"tcp"`
}

func generate40MailTCP(cfg GeneratorConfig) error {
	mailPath := filepath.Join(cfg.outputDir(), "40-mail-tcp.yml")

	if !cfg.MailEnabled {
		_ = os.Remove(mailPath)
		return nil
	}

	mailServices := filterByCategory(cfg.InfraServices, "mail-tcp")
	if len(mailServices) == 0 {
		_ = os.Remove(mailPath)
		return nil
	}

	tcpRouters := map[string]tcpRouterConfig{}
	tcpServices := map[string]tcpServiceConfig{}

	for _, svc := range mailServices {
		routerID := svc.EntryPoint // "smtp", "submission", "imaps", "managesieve"

		router := tcpRouterConfig{
			Rule:        "HostSNI(`*`)",
			EntryPoints: []string{svc.EntryPoint},
			Service:     routerID,
		}
		// IMAPS needs TLS passthrough
		if svc.EntryPoint == "imaps" {
			router.TLS = &tcpTLSConfig{Passthrough: true}
		}
		tcpRouters[routerID] = router

		tcpServices[routerID] = tcpServiceConfig{
			LoadBalancer: tcpLBConfig{Servers: []tcpServerConfig{
				{Address: fmt.Sprintf("%s:%d", svc.Host, svc.Port)},
			}},
		}
	}

	doc := mailTCPFile{
		TCP: tcpConfig{
			Routers:  tcpRouters,
			Services: tcpServices,
		},
	}
	return writeYAML(cfg.outputDir(), "40-mail-tcp.yml", doc)
}

// ── 50-tls.yml ───────────────────────────────────────────────────────────────

type tlsFileConfig struct {
	TLS tlsTopLevelConfig `yaml:"tls"`
}

func generate50TLS(cfg GeneratorConfig) error {
	if cfg.CertFile == "" || cfg.KeyFile == "" {
		// Remove stale file if it exists
		_ = os.Remove(filepath.Join(cfg.outputDir(), "50-tls.yml"))
		return nil
	}

	doc := tlsFileConfig{
		TLS: tlsTopLevelConfig{
			Stores: map[string]tlsStoreConfig{
				"default": {
					DefaultCertificate: &tlsCertRef{
						CertFile: cfg.CertFile,
						KeyFile:  cfg.KeyFile,
					},
				},
			},
		},
	}
	return writeYAML(cfg.outputDir(), "50-tls.yml", doc)
}

// ── helpers ──────────────────────────────────────────────────────────────────

// filterByCategory returns enabled InfraServices matching the given category.
func filterByCategory(svcs []InfraService, category string) []InfraService {
	var result []InfraService
	for _, s := range svcs {
		if s.Category == category && s.Enabled {
			result = append(result, s)
		}
	}
	return result
}

// findServiceByID returns the ID of a service if found, otherwise the id itself as fallback.
func findServiceByID(svcs []InfraService, id string) string {
	for _, s := range svcs {
		if s.ID == id {
			return id
		}
	}
	return id // fallback: return the requested id (router still points somewhere sensible)
}

// writeYAML marshals v to YAML and atomically writes outputDir/filename.
func writeYAML(dir, filename string, v any) error {
	data, err := yaml.Marshal(v)
	if err != nil {
		return fmt.Errorf("traefik generate %s: marshal: %w", filename, err)
	}

	dest := filepath.Join(dir, filename)
	tmp := dest + ".tmp"

	if err := os.WriteFile(tmp, []byte(fileHeader+string(data)), 0o644); err != nil {
		return fmt.Errorf("traefik generate %s: write tmp: %w", filename, err)
	}
	if err := os.Rename(tmp, dest); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("traefik generate %s: rename: %w", filename, err)
	}
	return nil
}
